@startuml
'https://plantuml.com/sequence-diagram

autonumber

'Outside
actor Player

'App
participant Main
participant QuestionUseCaseFactory

'View
participant ViewManager
participant QuestionView

'Interface Adapters (General)
participant ViewManagerModel
participant ViewModel

'Interface Adapters (Question)
participant QuestionViewModel
participant QuestionPresenter
participant QuestionController
participant QuestionState
participant JMapViewerTree

'Use Case
participant QuestionInteractor

'Data Access
participant MapDataAccessObject

Player -> Main: main
activate Main #yellow

Main -> ViewManagerModel: <<create>>
activate ViewManagerModel

Main <-- ViewManagerModel
deactivate ViewManagerModel

Main -> ViewManager: <<create>>
activate ViewManager

ViewManager -> ViewManagerModel: addPropertyChangeListener
activate ViewManagerModel

ViewManager <-- ViewManagerModel
deactivate ViewManagerModel

Main <-- ViewManager
deactivate ViewManager

Main -> QuestionViewModel: <<create>>
activate QuestionViewModel

QuestionViewModel -> ViewModel: <<create>>
activate ViewModel

QuestionViewModel <-- ViewModel
deactivate ViewModel

QuestionViewModel -> QuestionState: <<create>>
activate QuestionState

QuestionViewModel <-- QuestionState
deactivate QuestionState

Main <-- QuestionViewModel
deactivate QuestionViewModel

Main -> MapDataAccessObject: <<create>>
activate MapDataAccessObject

Main <-- MapDataAccessObject
deactivate MapDataAccessObject

Main -> QuestionUseCaseFactory: create
activate QuestionUseCaseFactory

QuestionUseCaseFactory -> QuestionUseCaseFactory: createQuestionUseCase
activate QuestionUseCaseFactory

QuestionUseCaseFactory -> QuestionPresenter: <<create>>
activate QuestionPresenter

QuestionUseCaseFactory <-- QuestionPresenter
deactivate QuestionPresenter

QuestionUseCaseFactory -> QuestionInteractor: <<create>>
activate QuestionInteractor

QuestionUseCaseFactory <-- QuestionInteractor
deactivate QuestionInteractor

QuestionUseCaseFactory -> QuestionController: <<create>>
activate QuestionController

QuestionUseCaseFactory <-- QuestionController
deactivate QuestionController

QuestionUseCaseFactory <-- QuestionUseCaseFactory
deactivate QuestionUseCaseFactory

QuestionUseCaseFactory -> QuestionView: <<create>>
activate QuestionView

QuestionView -> QuestionViewModel: addPropertyChangeListener
activate QuestionViewModel

QuestionView <-- QuestionViewModel
deactivate QuestionViewModel

QuestionView -> JMapViewerTree: <<create>>
activate JMapViewerTree

QuestionView <-- JMapViewerTree
deactivate JMapViewerTree

QuestionUseCaseFactory <-- QuestionView
deactivate QuestionView

Main <-- QuestionUseCaseFactory
deactivate QuestionUseCaseFactory

Main -> ViewManagerModel: firePropertyChanged
activate ViewManagerModel

Main <-- ViewManagerModel
deactivate ViewManagerModel

Player <-- Main
deactivate Main

@enduml